// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj2aTI45U6KHVbmigi2M9udNp3DWAwgLQ',
    appId: '1:437028462580:web:23d5be249a43424cade3a1',
    messagingSenderId: '437028462580',
    projectId: 'proyekambw-bc567',
    authDomain: 'proyekambw-bc567.firebaseapp.com',
    storageBucket: 'proyekambw-bc567.appspot.com',
    measurementId: 'G-7C8344F663',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuVNAmuV98K6OJ3Yiho4zWGHfSbMxzH1Q',
    appId: '1:437028462580:android:2450d7bed23c94eeade3a1',
    messagingSenderId: '437028462580',
    projectId: 'proyekambw-bc567',
    storageBucket: 'proyekambw-bc567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAosDv5Ax3DsfB7Ul_KQ0fOyXHkx8fnLJo',
    appId: '1:437028462580:ios:ff42eb5ad5b58d13ade3a1',
    messagingSenderId: '437028462580',
    projectId: 'proyekambw-bc567',
    storageBucket: 'proyekambw-bc567.appspot.com',
    iosClientId: '437028462580-jqp53b1nsastijkf2fk6fjeufppca3vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAosDv5Ax3DsfB7Ul_KQ0fOyXHkx8fnLJo',
    appId: '1:437028462580:ios:ff42eb5ad5b58d13ade3a1',
    messagingSenderId: '437028462580',
    projectId: 'proyekambw-bc567',
    storageBucket: 'proyekambw-bc567.appspot.com',
    iosClientId: '437028462580-jqp53b1nsastijkf2fk6fjeufppca3vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.reminderApp',
  );
}
